# Generated by Django 4.2.23 on 2025-08-12 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communityhub', '0005_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(related_name='community_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
